name: Python 程式碼執行

on:
 push:
   branches:
     - main
 workflow_dispatch:

jobs:
 run:
   runs-on: ubuntu-latest

   steps:
     - name: 檢出程式碼
       uses: actions/checkout@v4

     - name: 設定 Python 環境
       uses: actions/setup-python@v5
       with:
         python-version: '3.x'

     - name: 安裝依賴
       run: |
         python -m pip install --upgrade pip
         pip install yt-dlp

     - name: 執行 Python 程式
       run: python long_video_scraper.py

     - name: 上傳文字檔
       uses: actions/upload-artifact@v4
       with:
         name: long_videos
         path: long_videos.txt
 
